services:
  main:
    build:
      context: ./main
      dockerfile: Containerfile
    depends_on:
      delayed-health:
        condition: service_healthy
    ports:
      - "3301:3000"

  delayed-health:
    image: node:22-alpine
    command: [ "node", "/app/delayed-health.js" ]
    working_dir: /app
    volumes:
      - ./delayed-health:/app:ro,Z
    ports:
      - "3302:3000"
    healthcheck:
      test: [ "CMD", "node", "-e", "process.exit(1);" ]
      interval: 1s
      timeout: 5s
      retries: 3

x-pm3:
  hooks:
    all:
      started: ../hooks/zenity-state.sh
    main:
      stopping: ../hooks/zenity-state.sh
  startup:
    mode: watcher
    required_services:
      - main
